name: 🔀 Sync mirror to Gitee

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Sync:
    if: github.repository == '[github_repository_owner]/[github_repository_name]'
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:[github_repository_owner]/[github_repository_name]
          destination-repo: git@gitee.com:[gitee_repository_owner]/[gitee_repository_name]

