name: 🔀 Sync mirror to Gitee

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Sync:
    # TODO update github_repository_owner,github_repository_name,gitee_repository_owner,gitee_repository_name
    if: github.repository == '[github_repository_owner]/[github_repository_name]'
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: wearerequired/git-mirror-action@master
        env:
          # TODO update 获取：https://help.gitee.com/base/account/SSH%E5%85%AC%E9%92%A5%E8%AE%BE%E7%BD%AE
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:[github_repository_owner]/[github_repository_name]
          destination-repo: git@gitee.com:[gitee_repository_owner]/[gitee_repository_name]
